# Generated by Django 2.2.5 on 2019-09-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_photo', models.TextField()),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_party', models.CharField(max_length=50)),
                ('candidate_incumbency', models.CharField(max_length=100)),
            ],
        ),
    ]
